language: node_js

node_js:
  - '8'

env:
  global:
  - CC_TEST_REPORTER_ID=d46bc1a5b75f9835b34ee7f083417feca20b347a5de0524e3ae6579d948aaa94

branches:
  only:
    - master

cache:
  directories:
    - node_modules

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master

# before_install:
#   - rvm install 2.5.0

notifications:
  on_success: change
  on_failure: change

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - npm install

script:
  - npm run lint

sudo: false